// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace SalesSystem.DAL
{
    public partial class NotificationTypes
    {
        public NotificationTypes()
        {
            PromotionEventlistner = new HashSet<PromotionEventlistner>();
        }

        public string Name { get; set; }
        public int Id { get; set; }

        public virtual ICollection<PromotionEventlistner> PromotionEventlistner { get; set; }
    }
}