// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace SalesSystem.DAL
{
    public partial class Productdetails
    {
        public Productdetails()
        {
            Product = new HashSet<Product>();
            ProductAccesories = new HashSet<ProductAccesories>();
        }
        [DatabaseGeneratedAttribute(DatabaseGeneratedOption.Identity), Key()]
        public int Id { get; set; }
        public int ProductCategoryId { get; set; }
        public double Profitmargin { get; set; }
        public string Details { get; set; }
        public string Warrenty { get; set; }

        public virtual ProductCategory ProductCategory { get; set; }
        public virtual ICollection<Product> Product { get; set; }
        public virtual ICollection<ProductAccesories> ProductAccesories { get; set; }
    }
}