// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace SalesSystem.DAL
{
    public partial class ProductCategory
    {
        public ProductCategory()
        {
            Accesories = new HashSet<Accesories>();
            Productdetails = new HashSet<Productdetails>();
        }

        public int Id { get; set; }

        public virtual ICollection<Accesories> Accesories { get; set; }
        public virtual ICollection<Productdetails> Productdetails { get; set; }
    }
}