// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace SalesSystem.DAL
{
    public partial class ProductAccesories
    {
        public int Id { get; set; }
        public int AccesoryId { get; set; }
        public int ProductDetailsId { get; set; }

        public virtual Accesories Accesory { get; set; }
        public virtual Productdetails ProductDetails { get; set; }
    }
}