// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace SalesSystem.DAL
{
    [Table("ProductCategory")]
    public partial class ProductCategory
    {
        public ProductCategory()
        {
            Accesories = new HashSet<Accesory>();
            Productdetails = new HashSet<Productdetail>();
        }

        [Key]
        public int Id { get; set; }

        [InverseProperty(nameof(Accesory.ProductCategory))]
        public virtual ICollection<Accesory> Accesories { get; set; }
        [InverseProperty(nameof(Productdetail.ProductCategory))]
        public virtual ICollection<Productdetail> Productdetails { get; set; }
    }
}