// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace SalesSystem.DAL
{
    [Table("Product")]
    public partial class Product
    {
        public Product()
        {
            StockProducts = new HashSet<StockProduct>();
        }

        [Key]
        public int Id { get; set; }
        public int BrandId { get; set; }
        public int ProductDetailsId { get; set; }

        [ForeignKey(nameof(BrandId))]
        [InverseProperty("Products")]
        public virtual Brand Brand { get; set; }
        [ForeignKey(nameof(ProductDetailsId))]
        [InverseProperty(nameof(Productdetail.Products))]
        public virtual Productdetail ProductDetails { get; set; }
        [InverseProperty(nameof(StockProduct.Product))]
        public virtual ICollection<StockProduct> StockProducts { get; set; }
    }
}