// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace SalesSystem.DAL
{
    public partial class ProductAccesory
    {
        [Key]
        public int Id { get; set; }
        public int AccesoryId { get; set; }
        public int ProductDetailsId { get; set; }

        [ForeignKey(nameof(AccesoryId))]
        [InverseProperty("ProductAccesories")]
        public virtual Accesory Accesory { get; set; }
        [ForeignKey(nameof(ProductDetailsId))]
        [InverseProperty(nameof(Productdetail.ProductAccesories))]
        public virtual Productdetail ProductDetails { get; set; }
    }
}