// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace SalesSystem.DAL
{
    public partial class PromotionEventlistner
    {
        public int Id { get; set; }
        public int PromotionId { get; set; }
        public int EventListnerId { get; set; }
        public bool IsActive { get; set; }

        public virtual NotificationTypes EventListner { get; set; }
        public virtual Promotion Promotion { get; set; }
    }
}