// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace SalesSystem.DAL
{
    public partial class PublishedPromotions
    {
        public int PromotionId { get; set; }
        public DateTime Startdate { get; set; }
        public DateTime Enddate { get; set; }
        public decimal DiscountPercentage { get; set; }
        public int ProductId { get; set; }
        public int DealerId { get; set; }
        public int Id { get; set; }
    }
}