// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace SalesSystem.DAL
{
    [Table("StockProduct")]
    public partial class StockProduct
    {
        [Key]
        public int Id { get; set; }
        public int StockId { get; set; }
        public int ProductId { get; set; }

        [ForeignKey(nameof(ProductId))]
        [InverseProperty("StockProducts")]
        public virtual Product Product { get; set; }
        [ForeignKey(nameof(StockId))]
        [InverseProperty("StockProducts")]
        public virtual Stock Stock { get; set; }
    }
}