// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace SalesSystem.DAL
{
    public partial class Stock
    {
        public Stock()
        {
            StockProduct = new HashSet<StockProduct>();
        }

        public int Id { get; set; }
        public int? UserId { get; set; }

        public virtual User User { get; set; }
        public virtual ICollection<StockProduct> StockProduct { get; set; }
    }
}