// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace SalesSystem.DAL
{
    [Table("Stock")]
    public partial class Stock
    {
        public Stock()
        {
            StockProducts = new HashSet<StockProduct>();
        }

        [Key]
        public int Id { get; set; }
        public int? UserId { get; set; }

        [ForeignKey(nameof(UserId))]
        [InverseProperty("Stocks")]
        public virtual User User { get; set; }
        [InverseProperty(nameof(StockProduct.Stock))]
        public virtual ICollection<StockProduct> StockProducts { get; set; }
    }
}