// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace SalesSystem.DAL
{
    public partial class User
    {
        public User()
        {
            Stock = new HashSet<Stock>();
            UserDetails = new HashSet<UserDetails>();
        }

        public int Id { get; set; }
        public string Password { get; set; }
        public string UserName { get; set; }
        public bool IsActive { get; set; }
        public int RoleId { get; set; }

        public virtual Role Role { get; set; }
        public virtual ICollection<Stock> Stock { get; set; }
        public virtual ICollection<UserDetails> UserDetails { get; set; }
    }
}